version: "3.8"

services:
  backend:
    build:
      context: ./backend_agentic
    container_name: backend_agentic
    env_file:
      - .env
    ports:
      - "5001:5001"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
